name: Run-Golang-Core-API-CI

on:
  workflow_dispatch:
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - '.dockerignore'

permissions:
  contents: read

concurrency:
  # github.workflow: name of the workflow
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.2'
    
    - name: Install flyway
      id: install-flyway
      run: |
        FLYWAY_VERSION=10.3.0
        OS=linux-x64
        curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}-${OS}.tar.gz -o flyway-commandline-${FLYWAY_VERSION}.tar.gz \
          && tar -xzf flyway-commandline-${FLYWAY_VERSION}.tar.gz --strip-components=1 \
          && rm flyway-commandline-${FLYWAY_VERSION}.tar.gz \
          && ln -s $(realpath flyway) /usr/local/bin/flyway

    - name: Run integration tests
      id: integration-tests
      run: |
        cd api && make integration-test
